### ISSUE TITLE
[EM-2.1] First task in Praktikum 2

### ISSUE THREAD

**Issue by TadNodir** [WinataDaniel/E-Mensa_Werbeseite#5]
Vorbereitung. Bereiten Sie Ihre eingesetzte IDE für die Ausführung von PHP
Dateien vor.
1) Installieren Sie PHP (mindestens Version 8) auf Ihrem Computer.
2) Konfigurieren Sie Ihre IDE, so dass diese die neu installierte PHP-Installation
verwendet.
3) Erstellen Sie in Ihrer IDE eine Laufzeit-Konfiguration (z.B. mit Built-In PHPServer in PHPStorm) zur Ausführung von PHP Skripten.
4) Erstellen Sie eine Datei beispiele/erstesphp.php mit dem folgenden Inhalt:
<?php
echo "Erstes PHP Skript <br>";
phpinfo();
5) Rufen Sie diese Datei mit dem Webbrowser über den Built-In PHP-Server
auf (z.B. localhost:9050) und überprüfen Sie die korrekte Ausführung der
PHP Datei. Als Ergebnis sehen Sie die Ausgabe sowie die aktuelle
Konfiguration der PHP-Umgebung

**Comment by WinataDaniel** [comment]
Erledigt.
