### ISSUE TITLE
[EM-2.2] 2. Task in Praktikum 2

### ISSUE THREAD

**Issue by TadNodir** [WinataDaniel/E-Mensa_Werbeseite#6]
Übung PHP Grundlagen. Zur Einübung einer neuen Programmiersprache wollen
wir zunächst den grundlegenden Umgang mit der Sprache erlernen. Dazu steht für
Sie in ILIAS ein Test mit ersten Einführungsfragen zum Thema PHP bereit unter:
Praktikum > M2 > PHP Quiz
Führen Sie den Test so lange durch, bis Sie mit über 80% erreichten Punkten
bestehen. Jede/r Einzelne von Ihnen muss den Test bestehen. Eine Abgabe eines
einzelnen Teammitglieds reicht nicht aus. Sie können den Test beliebig oft
wiederholen. Sie müssen den Test bestehen, bevor die Abgabefrist des
Meilensteins endet.

**Comment by WinataDaniel** [comment]
Erledigt.
